"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";

import PoForm from "@/components/purchase-orders/PoForm";
import { createPurchaseOrder } from "@/lib/api";
import { usePermissions } from "@/lib/auth";

export default function NewPurchaseOrderPage() {
  const router = useRouter();
  const { has } = usePermissions();

  if (!has("po.create")) {
    return (
      <div className="max-w-[920px] mx-auto py-10 text-center text-[var(--color-ink-500)]">
        You do not have permission to create purchase orders.
      </div>
    );
  }

  return (
    <div className="max-w-[1080px] mx-auto pb-10">
      <header className="flex items-end justify-between gap-6 pb-4 mb-5 border-b border-[var(--color-border-default)]">
        <div>
          <div className="text-[12px] text-[var(--color-ink-500)] flex items-center gap-1.5 mb-1.5">
            <Link href="/procurement/purchase-orders" className="text-[var(--color-ink-500)] hover:text-[var(--color-navy-700)]">
              Procurement
            </Link>
            <span className="text-[var(--color-ink-300)]">/</span>
            <Link href="/procurement/purchase-orders" className="text-[var(--color-ink-500)] hover:text-[var(--color-navy-700)]">
              Purchase Orders
            </Link>
            <span className="text-[var(--color-ink-300)]">/</span>
            <span className="text-[var(--color-ink-900)] font-medium">New</span>
          </div>
          <h1 className="text-[24px] font-semibold text-[var(--color-ink-900)] m-0 tracking-[-0.01em]">
            New Purchase Order
          </h1>
          <div className="text-[13px] text-[var(--color-ink-500)] mt-1">
            Creates a DRAFT. The PO number is generated by the server. You can edit lines and totals until the PO is submitted.
          </div>
        </div>
      </header>

      <PoForm
        mode="create"
        onSubmit={async (body) => {
          const result = await createPurchaseOrder(body);
          if (result.kind === "ok") {
            router.replace(`/procurement/purchase-orders/${result.data.id}`);
          }
          return result;
        }}
      />
    </div>
  );
}
